# -*- coding: utf-8 -*-
# FONTE ÚNICA dos procedimentos. Alterou aqui, roda gera.py e as duas páginas mudam.
PROC = [
 ("cilios", "Cílios", [
  dict(id="volume-natural", nome="Volume Natural", val="150",
    desc="Para quem ama naturalidade, mas quer um olhar mais expressivo — um efeito semelhante ao rímel, porém mais delicado.",
    specs=[("Sessão","2h"),("Manutenção","15 a 20 dias")]),
  dict(id="efeito-rimel", nome="Efeito Rímel", val="170",
    desc="Para quem ama cílios mais marcantes e um olhar bem definido. Efeito semelhante ao rímel, mas sem borrar e sem precisar retocar.",
    specs=[("Sessão","2h"),("Dura","15 a 20 dias"),("","Sem manutenção")]),
  dict(id="volume-elegance", nome="Volume Elegance", val="180",
    desc="Para quem busca um olhar sofisticado e elegante sem perder a naturalidade.",
    specs=[("Sessão","2h"),("Manutenção","15 a 20 dias")]),
  dict(id="volume-brasileiro", nome="Volume Brasileiro", val="170",
    desc="Preenche as falhas que o rímel não resolve. O efeito que a cliente pede quando tem evento, viagem ou quer se sentir mais produzida.",
    specs=[("Sessão","2h"),("Manutenção","15 a 20 dias")]),
  dict(id="fox-eyes", nome="Fox Eyes", val="190",
    desc="Para quem ama um olhar mais alongado, moderno e marcante. Cria um visual mais puxadinho nos cantos externos dos olhos.",
    specs=[("Sessão","2h"),("Manutenção","15 a 20 dias")]),
  dict(id="lash", nome="Lash Lifting", val="150",
    desc="Curvatura no seu próprio cílio, sem fio sintético. Durabilidade de 45 a 60 dias, sem manutenção e sem cuidado especial.",
    specs=[("Sessão","2h"),("Dura","45 a 60 dias"),("","Sem manutenção")]),
 ]),
 ("sobrancelhas", "Sobrancelhas", [
  dict(id="design", nome="Design de sobrancelhas", val="55",
    desc="Realça o formato natural das suas sobrancelhas, deixando-as mais alinhadas.",
    specs=[("Sessão","30 min"),("Retorno","20 a 30 dias")]),
  dict(id="henna", nome="Design com henna", val="70",
    desc="Sobrancelhas prontas por 5 a 7 dias, sem precisar de sombra ou lápis.",
    specs=[("Sessão","50 min"),("Dura","5 a 7 dias"),("","Sem manutenção")]),
  dict(id="tintura", nome="Design com tintura", val="80",
    desc="Cor no fio, não na pele. Mais definição com aspecto natural — ideal para quem achou a henna marcada demais.",
    specs=[("Sessão","45 min"),("Dura","5 a 7 dias"),("","Sem manutenção")]),
  dict(id="brow-lamination", nome="Brow Lamination", val="190",
    desc="Alinha e organiza os fios, deixando as sobrancelhas com aparência mais cheia e definida. Corrige pequenas falhas.",
    specs=[("Sessão","1h30"),("Dura","30 a 45 dias")]),
  dict(id="sense-brows", nome="Sense Brows · reconstrução", val="500", unid="3 sessões",
    desc="Protocolo desenvolvido para estimular o crescimento das sobrancelhas. A partir de 3 sessões já é possível observar sinais de evolução, que variam de acordo com cada pessoa.",
    specs=[("Avaliação","30 min a 1h"),("","Tratamento personalizado")]),
 ]),
 ("labial", "Lábios", [
  dict(id="labial", nome="Micropigmentação labial", val="550",
    desc="Realça a cor e o contorno dos lábios, deixando-os mais definidos e uniformes. Ideal para quem busca um aspecto saudável e natural sem abrir mão da praticidade.",
    specs=[("Sessão","2h30"),("Retoque","45 dias"),("Dura","1 a 2 anos")]),
  dict(id="spa-labial", nome="Spa labial", val="120", unid="por sessão",
    desc="Hidrata e devolve a maciez aos lábios, removendo o aspecto ressecado. É também o preparo ideal antes da micropigmentação, favorecendo uma melhor fixação do pigmento.",
    specs=[("Sessão","40 min"),("","Sem manutenção")]),
 ]),
]
